Form sending actions
olimp-web/olimp_save_link_ext pull request #1
Opened 2020-04-10 11:57 UTC by ivanguy

2020-05-21 15:27 UTC, kotelnikov-itmo requested changes
Смотри комменты по коду. В остальном вроде выглядит рабочим. Подниму, проверю API и надо будет потестить

2020-05-21 15:27 UTC, kotelnikov-itmo commented on popup.js
> +            'Content-Type': 'application/json'
еще нужен заголовок с ключом авторизации. Он хранится в localstorage по ключу "token_". Задается на странице настроек расширения: https://github.com/olimp-web/olimp_save_link_ext/blob/master/options.js

2020-05-21 15:27 UTC, kotelnikov-itmo commented on popup.js
> +    document.getElementById('saveLinkForm').addEventListener("submit", sendFormXHR);
А почему не через fetch ?)

2020-05-21 18:06 UTC, ivanguy commented on popup.js
> +    document.getElementById('saveLinkForm').addEventListener("submit", sendFormXHR);
Решил попробовать потому что fetch без cors не заработал, так то через фетч надо верну

2020-05-25 08:25 UTC, ivanguy commented
бамп @kotelnikov-itmo

2020-05-28 15:00 UTC, kotelnikov-itmo approved these changes

2020-05-28 15:00 UTC, kotelnikov-itmo commented on popup.js
> +//    document.getElementById('saveLinkForm').addEventListener("submit", sendFormXHR);
а почему не XHR?)

2020-05-28 15:00 UTC, merged